database:
  host: localhost
  port: 5432
  username: myuser
  password: mypassword
  db: on-air
redis:
  host: localhost
  port: 6379
  password: redis
  db: 1
server:
  port: 2000
auth:
  secret-key: mysecretkey
  ExpiresIn: 240
